# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py38-django30

[testenv]
commands = {envpython} runtests.py {posargs}
deps =
    django30: Django==3.0
    py38-django30: mock==1.0.1
    py38-django30: ipdb
    py38-django30: requests==2.4.1
    py38-django30: vcrpy==1.1.2
    py38-django30: model_mommy
    py38-django30: python-dateutil==1.5
    py38-django30: django-discover-runner
